services:
  ram-ms-battle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ram-ms-battle
    restart: unless-stopped
    ports:
      - '3002:3002'
    env_file:
      - .env
    networks:
      - ram-shared-network

  redis:
    image: redis:7.2-alpine
    container_name: battle-redis
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    restart: always
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  redis_data:

networks:
  ram-shared-network:
    external: true
